# Generated by Django 3.1 on 2020-12-03 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign_up', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlist',
            name='pswd',
        ),
    ]
