# Generated by Django 3.1 on 2020-12-03 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_auto_20201203_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmember',
            name='projectlist',
        ),
        migrations.RemoveField(
            model_name='projectmember',
            name='userlist',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='ProjectMember',
        ),
    ]
