# Generated by Django 3.1 on 2020-12-14 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_auto_20201214_0457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='id',
        ),
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.IntegerField(default='SOME CATEGORY', primary_key=True, serialize=False),
        ),
    ]
