# Generated by Django 3.1 on 2020-12-14 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0004_auto_20201215_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
