# Generated by Django 3.1 on 2020-12-14 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0005_auto_20201215_0307'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Status_detail',
        ),
    ]
