# Generated by Django 3.1 on 2020-12-03 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sign_up', '0001_initial'),
        ('mainpage', '0005_auto_20201203_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmember',
            name='userlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sign_up.userlist'),
        ),
        migrations.AlterField(
            model_name='status',
            name='userlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sign_up.userlist'),
        ),
    ]
