# Generated by Django 3.1 on 2020-12-14 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0007_status_detail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Status_detail',
        ),
    ]
