# Generated by Django 3.1 on 2020-12-14 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0008_delete_status_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_id', models.IntegerField(default='SOME CATEGORY')),
                ('detail', models.CharField(default='', max_length=10)),
                ('projectlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.project')),
            ],
        ),
    ]
