# Generated by Django 2.1.5 on 2020-12-05 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0008_invite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invite',
            name='invite_user',
        ),
        migrations.RemoveField(
            model_name='invite',
            name='invited_user',
        ),
        migrations.RemoveField(
            model_name='invite',
            name='project_name',
        ),
        migrations.DeleteModel(
            name='Invite',
        ),
    ]
