# Generated by Django 2.1.5 on 2020-12-05 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0010_invite'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='message',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='projectmember',
            name='role',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.IntegerField(),
        ),
    ]
