# Generated by Django 2.1.5 on 2020-12-05 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0011_auto_20201205_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invite',
            name='invite_user',
        ),
        migrations.RemoveField(
            model_name='invite',
            name='invited_user',
        ),
        migrations.RemoveField(
            model_name='invite',
            name='project_name',
        ),
        migrations.DeleteModel(
            name='Invite',
        ),
    ]
